# make sure **ALL** tools here are in pyproject.toml as:
#   - listed as dev-dependencies
#   - version specifiers are **EXACTLY** the same
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.2
    hooks:
      - id: ruff
        args:
          - --fix
          - --line-length=100
          - --ignore=E501,W293,E303,W291,E203,E731,E231,E721,E722,E741
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args:
          - --follow-imports=silent
          - --show-column-numbers
          - --ignore-missing-imports
          - --warn-unreachable
          - --install-types
          - --non-interactive
          - --check-untyped-defs
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # https://github.com/pre-commit/pre-commit-hooks/releases
    hooks:
      - id: check-added-large-files
        args:
          - '--maxkb=1024' # 1MB file limit
      - id: check-ast
        language: python
      - id: check-case-conflict
        language: python
      - id: check-json
        language: python
      - id: check-merge-conflict
        language: python
      - id: check-shebang-scripts-are-executable
        language: python
      - id: check-symlinks
        language: python
      - id: check-toml
        language: python
      - id: check-yaml
        language: python
        args:
          - '--allow-multiple-documents'


