[tool.poetry]
name = "pywise"
version = "0.4.0"
description = "Robust serialization support for NamedTuple & @dataclass data types."
authors = ["Malcolm Greaves <greaves.malcolm@gmail.com>"]
homepage = "https://github.com/malcolmgreaves/pywise"
license = "Apache-2.0"
readme = 'README.md'
exclude = ['core_utils/support_for_testing.py'] # NEVER INCLUDE THIS FILE (!)
packages = [
    { include = "core_utils" },
]


[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
mypy = "^1.3"
black = "^23.3"
flake8 = "*"
ipython = "*"
ipdb = "*"
pyyaml = "*"
tox = "^4.5"
numpy = "^1.21"
torch = "*"
pytest-cov = "*"
coveralls = "*"

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
